# In root directory
# Create render.yaml
services:
  - type: web
    name: carpooling-backend
    env: node
    buildCommand: cd carpooling-backend && npm install
    startCommand: cd carpooling-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: dpg-ctheb2jtq21c739mjtjg-a
      - key: DB_USER
        value: carpooling_wlx7_user
      - key: DB_PASSWORD
        value: XWdjMTP5jFtAELhghwsZ3qgQV9Ij7Xm1
      - key: DB_NAME
        value: carpooling_wlx7
      - key: JWT_SECRET
        value: 5d99e437893f12f1b8c0419d13f8f0b8e772ab88f26f5075d7d15c8b3777d453
      - key: EMAIL_USER
        value: varunshankaralt@gmail.com
      - key: EMAIL_PASS
        value: symc mspl uoin zmwo

  - type: web
    name: carpooling-frontend
    env: static
    buildCommand: cd carpooling-frontend && npm install && npm run build
    staticPublishPath: ./carpooling-frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://YOUR_BACKEND_URL